discord_token: discord-token
telegram_token: telegram-token
output_chat_id: telegram-chat-id-to-output-messages

allowed_guilds_ids: []
muted_guilds_ids: []

allowed_channels_ids: []
muted_channels_ids: []

allowed_users_ids: []
muted_users_ids: []
